const JOB_DATA = [
    {
        "id": "job_001",
        "title": "SDE Intern",
        "company": "Amazon",
        "location": "Bangalore",
        "mode": "Hybrid",
        "experience": "Fresher",
        "skills": ["Java", "DSA", "AWS"],
        "source": "LinkedIn",
        "postedDaysAgo": 2,
        "salaryRange": "₹40k–₹80k/month Internship",
        "applyUrl": "https://amazon.jobs",
        "description": "Join amazon as an SDE Intern. You will work on distributed systems and learn meaningful AWS technologies. Ideal for final year students."
    },
    {
        "id": "job_002",
        "title": "Frontend Developer",
        "company": "Swiggy",
        "location": "Bangalore",
        "mode": "Onsite",
        "experience": "1-3",
        "skills": ["React", "Redux", "Tailwind"],
        "source": "Naukri",
        "postedDaysAgo": 0,
        "salaryRange": "12–18 LPA",
        "applyUrl": "https://careers.swiggy.com",
        "description": "Build pixel-perfect UI for Swiggy's consumer app. Experience with React and performance optimization is a must."
    },
    {
        "id": "job_003",
        "title": "Graduate Engineer Trainee",
        "company": "TCS",
        "location": "Pune",
        "mode": "Onsite",
        "experience": "Fresher",
        "skills": ["Python", "SQL", "Communication"],
        "source": "TCS Careers",
        "postedDaysAgo": 5,
        "salaryRange": "3.5–5 LPA",
        "applyUrl": "https://tcs.com/careers",
        "description": "TCS is hiring fresh graduates for the Ninja profile. Strong aptitude and basic programming knowledge required."
    },
    {
        "id": "job_004",
        "title": "Backend Engineer",
        "company": "Razorpay",
        "location": "Bangalore",
        "mode": "Remote",
        "experience": "1-3",
        "skills": ["Go", "PostgreSQL", "Microservices"],
        "source": "LinkedIn",
        "postedDaysAgo": 1,
        "salaryRange": "18–24 LPA",
        "applyUrl": "https://razorpay.com/jobs",
        "description": "Scale payments infrastructure at Razorpay. Looking for Go developers with strong database fundamentals."
    },
    {
        "id": "job_005",
        "title": "Data Analyst Intern",
        "company": "Flipkart",
        "location": "Bangalore",
        "mode": "Hybrid",
        "experience": "Fresher",
        "skills": ["Python", "SQL", "Excel"],
        "source": "Hacthon",
        "postedDaysAgo": 3,
        "salaryRange": "₹30k–₹50k/month Internship",
        "applyUrl": "https://flipkartcareers.com",
        "description": "Analyze e-commerce trends and generate reports. Python/Pandas proficiency preferred."
    },
    {
        "id": "job_006",
        "title": "Java Developer",
        "company": "Infosys",
        "location": "Mysore",
        "mode": "Onsite",
        "experience": "0-1",
        "skills": ["Java", "Spring Boot", "Hibernate"],
        "source": "Naukri",
        "postedDaysAgo": 4,
        "salaryRange": "4–6 LPA",
        "applyUrl": "https://infosys.com/careers",
        "description": "Systems Engineer role. Training provided at Mysore campus. Java basics mandatory."
    },
    {
        "id": "job_007",
        "title": "Product Designer",
        "company": "CRED",
        "location": "Bangalore",
        "mode": "Onsite",
        "experience": "1-3",
        "skills": ["Figma", "UI/UX", "Prototyping"],
        "source": "LinkedIn",
        "postedDaysAgo": 1,
        "salaryRange": "15–25 LPA",
        "applyUrl": "https://cred.club/careers",
        "description": "Design high-fidelity interfaces for the CRED app. Looking for a distinct visual style."
    },
    {
        "id": "job_008",
        "title": "DevOps Engineer",
        "company": "PhonePe",
        "location": "Pune",
        "mode": "Hybrid",
        "experience": "3-5",
        "skills": ["Kubernetes", "Docker", "CI/CD"],
        "source": "Indeed",
        "postedDaysAgo": 2,
        "salaryRange": "20–30 LPA",
        "applyUrl": "https://phonepe.com/careers",
        "description": "Manage PhonePe's massive scale infrastructure. K8s expertise essential."
    },
    {
        "id": "job_009",
        "title": "QA Engineer",
        "company": "Wipro",
        "location": "Hyderabad",
        "mode": "Onsite",
        "experience": "0-1",
        "skills": ["Selenium", "Java", "Testing"],
        "source": "Naukri",
        "postedDaysAgo": 6,
        "salaryRange": "3.5–5 LPA",
        "applyUrl": "https://wipro.com/careers",
        "description": "Automation testing role using Selenium. Good understanding of SDLC required."
    },
    {
        "id": "job_010",
        "title": "Full Stack Developer",
        "company": "Zoho",
        "location": "Chennai",
        "mode": "Onsite",
        "experience": "1-3",
        "skills": ["Java", "Ember.js", "MySQL"],
        "source": "Zoho Careers",
        "postedDaysAgo": 0,
        "salaryRange": "8–12 LPA",
        "applyUrl": "https://zoho.com/careers",
        "description": "Build SaaS products at Zoho. Unique culture, strictly onsite in Chennai/Tenkasi."
    },
    {
        "id": "job_011",
        "title": "React Native Developer",
        "company": "Juspay",
        "location": "Bangalore",
        "mode": "Hybrid",
        "experience": "1-3",
        "skills": ["React Native", "Redux", "Mobile"],
        "source": "LinkedIn",
        "postedDaysAgo": 7,
        "salaryRange": "14–20 LPA",
        "applyUrl": "https://juspay.in/careers",
        "description": "Build payments SDKs used by millions. Functional programming mindset is a plus."
    },
    {
        "id": "job_012",
        "title": "Software Engineer",
        "company": "Microsoft",
        "location": "Hyderabad",
        "mode": "Hybrid",
        "experience": "Fresher",
        "skills": ["C++", "C#", "Algorithms"],
        "source": "Careers Page",
        "postedDaysAgo": 1,
        "salaryRange": "16–25 LPA",
        "applyUrl": "https://careers.microsoft.com",
        "description": "Entry level SDE role. Working on Azure or Office 365 teams."
    },
    {
        "id": "job_013",
        "title": "Cloud Support Associate",
        "company": "Amazon",
        "location": "Bangalore",
        "mode": "Onsite",
        "experience": "0-1",
        "skills": ["Linux", "Networking", "AWS"],
        "source": "Naukri",
        "postedDaysAgo": 3,
        "salaryRange": "5–8 LPA",
        "applyUrl": "https://amazon.jobs",
        "description": "Support AWS enterprise customers. Strong networking and OS fundamentals needed."
    },
    {
        "id": "job_014",
        "title": "Associate Consultant",
        "company": "Capgemini",
        "location": "Mumbai",
        "mode": "Hybrid",
        "experience": "1-3",
        "skills": ["Java", ".NET", "SQL"],
        "source": "Naukri",
        "postedDaysAgo": 8,
        "salaryRange": "6–9 LPA",
        "applyUrl": "https://capgemini.com",
        "description": "Client facing role. Must have good communication and technical basics."
    },
    {
        "id": "job_015",
        "title": "Python Developer",
        "company": "Accenture",
        "location": "Gurgaon",
        "mode": "Hybrid",
        "experience": "1-3",
        "skills": ["Python", "Django", "Rest API"],
        "source": "LinkedIn",
        "postedDaysAgo": 4,
        "salaryRange": "8–12 LPA",
        "applyUrl": "https://accenture.com/careers",
        "description": "Developing backend services for global clients using Django/Flask."
    },
    {
        "id": "job_016",
        "title": "Machine Learning Intern",
        "company": "Google",
        "location": "Bangalore",
        "mode": "Onsite",
        "experience": "Fresher",
        "skills": ["TensorFlow", "Python", "Math"],
        "source": "Google Careers",
        "postedDaysAgo": 0,
        "salaryRange": "₹80k–₹1L/month Internship",
        "applyUrl": "https://careers.google.com",
        "description": "Research internship. Work with state of the art models."
    },
    {
        "id": "job_017",
        "title": "Business Analyst",
        "company": "Deloitte",
        "location": "Hyderabad",
        "mode": "Hybrid",
        "experience": "0-1",
        "skills": ["Excel", "Tableau", "SQL"],
        "source": "Naukri",
        "postedDaysAgo": 5,
        "salaryRange": "6–9 LPA",
        "applyUrl": "https://deloitte.com",
        "description": "Analyze business requirements and translate to technical specs."
    },
    {
        "id": "job_018",
        "title": "Android Developer",
        "company": "Zomato",
        "location": "Gurgaon",
        "mode": "Onsite",
        "experience": "1-3",
        "skills": ["Kotlin", "Android Studio", "MVVM"],
        "source": "LinkedIn",
        "postedDaysAgo": 2,
        "salaryRange": "15–22 LPA",
        "applyUrl": "https://zomato.com/careers",
        "description": "Build features for the Zomato delivery partner app."
    },
    {
        "id": "job_019",
        "title": "Software Engineer",
        "company": "Oracle",
        "location": "Bangalore",
        "mode": "Hybrid",
        "experience": "1-3",
        "skills": ["Java", "Oracle DB", "Cloud"],
        "source": "LinkedIn",
        "postedDaysAgo": 6,
        "salaryRange": "14–20 LPA",
        "applyUrl": "https://oracle.com/careers",
        "description": "OCI (Oracle Cloud Infrastructure) team hiring for backend roles."
    },
    {
        "id": "job_020",
        "title": "Systems Analyst",
        "company": "Cognizant",
        "location": "Chennai",
        "mode": "Onsite",
        "experience": "3-5",
        "skills": ["Mainframe", "Cobol", "DB2"],
        "source": "Naukri",
        "postedDaysAgo": 9,
        "salaryRange": "8–12 LPA",
        "applyUrl": "https://cognizant.com",
        "description": "Legacy modernization projects. Requires specific mainframe expertise."
    },
    { "id": "job_021", "title": "Frontend Engineer", "company": "Freshworks", "location": "Chennai", "mode": "Onsite", "experience": "1-3", "skills": ["Ember", "JS", "CSS"], "source": "LinkedIn", "postedDaysAgo": 2, "salaryRange": "10-15 LPA", "applyUrl": "https://freshworks.com", "description": "Work on Freshdesk UI." },
    { "id": "job_022", "title": "SDE-1", "company": "Meesho", "location": "Bangalore", "mode": "Remote", "experience": "0-1", "skills": ["Java", "Spring", "Kafka"], "source": "LinkedIn", "postedDaysAgo": 1, "salaryRange": "18-25 LPA", "applyUrl": "https://meesho.io", "description": "High scale e-commerce challenges." },
    { "id": "job_023", "title": "Analyst", "company": "Goldman Sachs", "location": "Bangalore", "mode": "Hybrid", "experience": "Fresher", "skills": ["C++", "Math", "Quant"], "source": "Careers Page", "postedDaysAgo": 3, "salaryRange": "20-25 LPA", "applyUrl": "https://gs.com", "description": "Financial modelling and algos." },
    { "id": "job_024", "title": "Tech Support", "company": "Dell", "location": "Bangalore", "mode": "Onsite", "experience": "0-1", "skills": ["Hardware", "Windows", "Troubleshooting"], "source": "Naukri", "postedDaysAgo": 5, "salaryRange": "4-6 LPA", "applyUrl": "https://dell.com", "description": "Internal IT support role." },
    { "id": "job_025", "title": "SAP Consultant", "company": "IBM", "location": "Pune", "mode": "Hybrid", "experience": "3-5", "skills": ["ABAP", "SAP HANA"], "source": "LinkedIn", "postedDaysAgo": 7, "salaryRange": "12-18 LPA", "applyUrl": "https://ibm.com", "description": "SAP Implementation project." },
    { "id": "job_026", "title": "iOS Intern", "company": "Smallcase", "location": "Bangalore", "mode": "Onsite", "experience": "Fresher", "skills": ["Swift", "iOS"], "source": "Internshala", "postedDaysAgo": 1, "salaryRange": "₹25k/month", "applyUrl": "https://smallcase.com", "description": "Assist iOS team with new features." },
    { "id": "job_027", "title": "Marketing Intern", "company": "Zerodha", "location": "Bangalore", "mode": "Onsite", "experience": "Fresher", "skills": ["Content", "Social Media"], "source": "Zerodha Careers", "postedDaysAgo": 4, "salaryRange": "₹20k/month", "applyUrl": "https://zerodha.com", "description": "Learn fintech marketing." },
    { "id": "job_028", "title": "Golang Developer", "company": "Gojek", "location": "Bangalore", "mode": "Remote", "experience": "3-5", "skills": ["Go", "Distributed Systems"], "source": "LinkedIn", "postedDaysAgo": 0, "salaryRange": "30-50 LPA", "applyUrl": "https://gojek.com", "description": "Superapp backend scale." },
    { "id": "job_029", "title": "Cyber Security Analyst", "company": "Palo Alto Networks", "location": "Bangalore", "mode": "Hybrid", "experience": "1-3", "skills": ["Network Security", "Python"], "source": "LinkedIn", "postedDaysAgo": 6, "salaryRange": "15-20 LPA", "applyUrl": "https://paloaltonetworks.com", "description": "Threat analysis and response." },
    { "id": "job_030", "title": "React Developer", "company": "Myntra", "location": "Bangalore", "mode": "Hybrid", "experience": "1-3", "skills": ["React", "Node.js"], "source": "Naukri", "postedDaysAgo": 2, "salaryRange": "14-18 LPA", "applyUrl": "https://myntra.com", "description": "Fashion e-commerce frontend." },
    { "id": "job_031", "title": "Data Scientist", "company": "Fractal", "location": "Mumbai", "mode": "Hybrid", "experience": "1-3", "skills": ["Python", "ML", "Statistics"], "source": "LinkedIn", "postedDaysAgo": 3, "salaryRange": "10-15 LPA", "applyUrl": "https://fractal.ai", "description": "AI solutions for clients." },
    { "id": "job_032", "title": "SDE-2", "company": "Uber", "location": "Bangalore", "mode": "Hybrid", "experience": "3-5", "skills": ["Java", "Go", "System Design"], "source": "Uber Careers", "postedDaysAgo": 8, "salaryRange": "40-60 LPA", "applyUrl": "https://uber.com", "description": "Core infrastructure team." },
    { "id": "job_033", "title": "Product Manager", "company": "Paytm", "location": "Noida", "mode": "Onsite", "experience": "3-5", "skills": ["Product Strategy", "Analytics"], "source": "LinkedIn", "postedDaysAgo": 5, "salaryRange": "20-30 LPA", "applyUrl": "https://paytm.com", "description": "Lead payments product vertical." },
    { "id": "job_034", "title": "UX Researcher", "company": "MakeMyTrip", "location": "Gurgaon", "mode": "Hybrid", "experience": "1-3", "skills": ["User Research", "Figma"], "source": "Naukri", "postedDaysAgo": 2, "salaryRange": "10-14 LPA", "applyUrl": "https://makemytrip.com", "description": "Travel booking experience research." },
    { "id": "job_035", "title": "PHP Developer", "company": "Naukri.com", "location": "Noida", "mode": "Onsite", "experience": "1-3", "skills": ["PHP", "Laravel"], "source": "Naukri", "postedDaysAgo": 4, "salaryRange": "6-10 LPA", "applyUrl": "https://infoedge.in", "description": "Maintain Naukri's core backend." },
    { "id": "job_036", "title": "SRE", "company": "LinkedIn", "location": "Bangalore", "mode": "Hybrid", "experience": "3-5", "skills": ["Linux", "Python", "Automation"], "source": "LinkedIn", "postedDaysAgo": 1, "salaryRange": "35-50 LPA", "applyUrl": "https://linkedin.com", "description": "Site reliability for LinkedIn platform." },
    { "id": "job_037", "title": "Blockchain Dev", "company": "CoinSwitch", "location": "Bangalore", "mode": "Remote", "experience": "1-3", "skills": ["Solidity", "Rust", "Web3"], "source": "Wellfound", "postedDaysAgo": 7, "salaryRange": "18-25 LPA", "applyUrl": "https://coinswitch.co", "description": "Crypto exchange infrastructure." },
    { "id": "job_038", "title": "Game Developer", "company": "Zynga", "location": "Bangalore", "mode": "Hybrid", "experience": "1-3", "skills": ["Unity", "C#"], "source": "LinkedIn", "postedDaysAgo": 5, "salaryRange": "12-18 LPA", "applyUrl": "https://zynga.com", "description": "Mobile game development." },
    { "id": "job_039", "title": "Ruby Developer", "company": "Gojek", "location": "Bangalore", "mode": "Remote", "experience": "3-5", "skills": ["Ruby", "Rails"], "source": "LinkedIn", "postedDaysAgo": 10, "salaryRange": "25-35 LPA", "applyUrl": "https://gojek.com", "description": "Backend services." },
    { "id": "job_040", "title": "QA Automation", "company": "BrowserStack", "location": "Mumbai", "mode": "Remote", "experience": "1-3", "skills": ["Java", "Selenium"], "source": "LinkedIn", "postedDaysAgo": 3, "salaryRange": "10-15 LPA", "applyUrl": "https://browserstack.com", "description": "Testing tools development." },
    { "id": "job_041", "title": "Technical Writer", "company": "Salesforce", "location": "Hyderabad", "mode": "Hybrid", "experience": "3-5", "skills": ["Documentation", "API Specs"], "source": "Careers Page", "postedDaysAgo": 6, "salaryRange": "12-16 LPA", "applyUrl": "https://salesforce.com", "description": "Developer documentation." },
    { "id": "job_042", "title": "Support Engineer", "company": "Freshworks", "location": "Chennai", "mode": "Onsite", "experience": "0-1", "skills": ["Communication", "Debugging"], "source": "Naukri", "postedDaysAgo": 2, "salaryRange": "4-6 LPA", "applyUrl": "https://freshworks.com", "description": "Customer technical support." },
    { "id": "job_043", "title": "Graphic Designer", "company": "Zomato", "location": "Gurgaon", "mode": "Onsite", "experience": "1-3", "skills": ["Photoshop", "Illustrator"], "source": "LinkedIn", "postedDaysAgo": 4, "salaryRange": "6-10 LPA", "applyUrl": "https://zomato.com", "description": "Marketing collaterals." },
    { "id": "job_044", "title": "HR Intern", "company": "Ola", "location": "Bangalore", "mode": "Onsite", "experience": "Fresher", "skills": ["Communication", "Excel"], "source": "Internshala", "postedDaysAgo": 1, "salaryRange": "₹15k/month", "applyUrl": "https://olacabs.com", "description": "Recruitment coordination." },
    { "id": "job_045", "title": "Sales Associate", "company": "Byju's", "location": "Bangalore", "mode": "Onsite", "experience": "0-1", "skills": ["Sales", "Hindi", "English"], "source": "Naukri", "postedDaysAgo": 0, "salaryRange": "4-7 LPA", "applyUrl": "https://byjus.com", "description": "Business development role." },
    { "id": "job_046", "title": "Full Stack Intern", "company": "Groww", "location": "Bangalore", "mode": "Hybrid", "experience": "Fresher", "skills": ["React", "Node"], "source": "LinkedIn", "postedDaysAgo": 2, "salaryRange": "₹30k/month", "applyUrl": "https://groww.in", "description": "Investment platform features." },
    { "id": "job_047", "title": "NetSuite Developer", "company": "Oracle", "location": "Hyderabad", "mode": "Hybrid", "experience": "3-5", "skills": ["NetSuite", "JS"], "source": "LinkedIn", "postedDaysAgo": 7, "salaryRange": "12-18 LPA", "applyUrl": "https://oracle.com", "description": "ERP customization." },
    { "id": "job_048", "title": "Network Engineer", "company": "Cisco", "location": "Bangalore", "mode": "Hybrid", "experience": "1-3", "skills": ["CCNA", "Routing"], "source": "Careers Page", "postedDaysAgo": 5, "salaryRange": "8-12 LPA", "applyUrl": "https://cisco.com", "description": "Network infrastructure." },
    { "id": "job_049", "title": "Security Engineer", "company": "CrowdStrike", "location": "Pune", "mode": "Remote", "experience": "3-5", "skills": ["Security", "Cloud"], "source": "LinkedIn", "postedDaysAgo": 3, "salaryRange": "25-35 LPA", "applyUrl": "https://crowdstrike.com", "description": "Endpoint protection." },
    { "id": "job_050", "title": "Data Engineer", "company": "Walmart", "location": "Bangalore", "mode": "Hybrid", "experience": "1-3", "skills": ["Hadoop", "Spark", "SQL"], "source": "LinkedIn", "postedDaysAgo": 1, "salaryRange": "14-20 LPA", "applyUrl": "https://walmart.com", "description": "Big data pipelines." },
    { "id": "job_051", "title": "System Admin", "company": "HCL", "location": "Noida", "mode": "Onsite", "experience": "1-3", "skills": ["Windows Server", "VMware"], "source": "Naukri", "postedDaysAgo": 4, "salaryRange": "4-7 LPA", "applyUrl": "https://hcl.com", "description": "Server maintenance." },
    { "id": "job_052", "title": "Flutter Developer", "company": "Dream11", "location": "Mumbai", "mode": "Hybrid", "experience": "1-3", "skills": ["Flutter", "Dart"], "source": "LinkedIn", "postedDaysAgo": 2, "salaryRange": "15-22 LPA", "applyUrl": "https://dream11.com", "description": "Fantasy sports app." },
    { "id": "job_053", "title": "Content Writer", "company": "Pocket FM", "location": "Bangalore", "mode": "Onsite", "experience": "1-3", "skills": ["Writing", "Creative"], "source": "LinkedIn", "postedDaysAgo": 6, "salaryRange": "5-8 LPA", "applyUrl": "https://pocketfm.com", "description": "Audio series scripts." },
    { "id": "job_054", "title": "Video Editor", "company": "Ultrahuman", "location": "Bangalore", "mode": "Onsite", "experience": "1-3", "skills": ["Premiere Pro", "After Effects"], "source": "LinkedIn", "postedDaysAgo": 3, "salaryRange": "6-10 LPA", "applyUrl": "https://ultrahuman.com", "description": "Marketing videos." },
    { "id": "job_055", "title": "Frontend Architect", "company": "Atlassian", "location": "Bangalore", "mode": "Remote", "experience": "5+", "skills": ["React", "System Design"], "source": "LinkedIn", "postedDaysAgo": 8, "salaryRange": "50-70 LPA", "applyUrl": "https://atlassian.com", "description": "Jira frontend architecture." },
    { "id": "job_056", "title": "Staff Engineer", "company": "Intuit", "location": "Bangalore", "mode": "Hybrid", "experience": "5+", "skills": ["Java", "Spring", "AWS"], "source": "LinkedIn", "postedDaysAgo": 9, "salaryRange": "45-65 LPA", "applyUrl": "https://intuit.com", "description": "QuickBooks platform." },
    { "id": "job_057", "title": "Principal Engineer", "company": "MakeMyTrip", "location": "Gurgaon", "mode": "Hybrid", "experience": "5+", "skills": ["Java", "Microservices"], "source": "Naukri", "postedDaysAgo": 4, "salaryRange": "40-60 LPA", "applyUrl": "https://makemytrip.com", "description": "Flight booking engine." },
    { "id": "job_058", "title": "Engineering Manager", "company": "Urban Company", "location": "Gurgaon", "mode": "Onsite", "experience": "5+", "skills": ["Management", "Tech"], "source": "LinkedIn", "postedDaysAgo": 5, "salaryRange": "40-70 LPA", "applyUrl": "https://urbancompany.com", "description": "Lead partner app team." },
    { "id": "job_059", "title": "Director of Engineering", "company": "Unacademy", "location": "Bangalore", "mode": "Hybrid", "experience": "8+", "skills": ["Leadership", "Scale"], "source": "LinkedIn", "postedDaysAgo": 2, "salaryRange": "80L-1Cr", "applyUrl": "https://unacademy.com", "description": "Edtech scale." },
    { "id": "job_060", "title": "CTO", "company": "Early Stage Stealth", "location": "Bangalore", "mode": "Onsite", "experience": "5+", "skills": ["Everything"], "source": "Twitter", "postedDaysAgo": 0, "salaryRange": "Equity + Stipend", "applyUrl": "#", "description": "Build from scratch." }
];
